### ISSUE TITLE
Choosing a Name for the Project

### ISSUE THREAD

**Issue by MaxBondABE** [mos-dev-wiki/meta#1]
We need a name for the project!

Put forward candidate names, and we'll choose one.

**Comment by AbleTheAbove** [comment]
Modern Operating System Developer Wiki
mos-dev wiki

**Comment by Soveu** [comment]
Cooler OSDev @repnop
Real Mode Must Die

**Comment by Evrey** [comment]
- [ ] COSDEW — Cooler OS DEv Wiki
- [ ] NaDOS Wiki — Not a Disk Operating System Wiki (as in don't just repeat old stuff)
- [ ] RMMD Wiki — Real Mode Must Die Wiki (similar idea)
- [ ] NovOS Wiki — Novum OS Wiki

**Comment by Soveu** [comment]
No Fork Allowed (kinda a reference to "no fun allowed")

**Comment by MaxBondABE** [comment]
Point of information, we _can_ rename the organization, and it _will_ change the URL from this ugly one.

**Comment by Evrey** [comment]
I'll make one post for each suggestion. React to them with thumbs up or down to vote.

**Comment by Evrey** [comment]
**mos-dev wiki — Modern Operating System Developer Wiki**

**Comment by Evrey** [comment]
**COSDEW — Cooler OS DEv Wiki**

**Comment by Evrey** [comment]
**RMMD — Real Mode Must Die**

**Comment by Evrey** [comment]
**NaDOS Wiki — Not a Disk Operating System Wiki**

**Comment by Evrey** [comment]
**NovOS Wiki — Novum OS Wiki**

**Comment by Evrey** [comment]
**No Fork Allowed**

**Comment by AbleTheAbove** [comment]
It's been 24 hours (roughly//rounding up) And I think the results are pretty clear .-.
Anyone radically opposed to mos-dev wiki?

**Comment by MaxBondABE** [comment]
I'm good with that.

**Comment by AbleTheAbove** [comment]
Marking as closed 🥇
